### ISSUE TITLE
Asks for segment size although it's already been given

### ISSUE THREAD

**Issue by ShapeShifter499** [seiferma/splitviewfuse#2]
The following command results in error, why?

```
splitviewfuse /run/media/lance/0afd4383-73bb-4234-bba0-f69b261248c3/ /mnt/split/ -o segmentsize8000000000
Error during command line parsing: argument -o: The segment size option is mandatory.
```

**Comment by ShapeShifter499** [comment]
You need to fix a typo in your readme as the "segmentsize" variable requires a equal sign (=) as you probably already know.

**Comment by seiferma** [comment]
Thanks for pointing this out. I fixed the documentation on Github and pypi.
