### ISSUE TITLE
[Question] Can files that are segmented be joined without unionviewfuse?

### ISSUE THREAD

**Issue by ShapeShifter499** [seiferma/splitviewfuse#3]
In case of a emergency, say my files are split on the cloud and I need them now but I don't have a fuse system nearby. Is it possible to join the files manually?

**Comment by seiferma** [comment]
Yes, you can. The filesystem simply splits the files without adding any additional meta data to them. So, you can just use `cat file.seg.0 file.seg.1 > file` on unix or `copy /b file.seg.0 file.seg.1 file` on windows.

**Comment by ShapeShifter499** [comment]
Thanks!. That's what I figured but I didn't want to screw up my files
