### ISSUE TITLE
[Request] Adding your package to Arch Linux/AUR

### ISSUE THREAD

**Issue by ShapeShifter499** [seiferma/splitviewfuse#4]
Hi,

I'm requesting permission to add your package to the AUR (Arch User Repository) which in turn has the potential to be accepted to the official community repository of Arch Linux if up voted enough. If granted permission I will make sure this submitted package correctly credits you and your GitHub page.

Regards,
Lance

**Comment by seiferma** [comment]
Hi Lance,

I like the idea of an easy to use distribution package. I'm perfectly fine with adding my filesystem to the arch repository. I'll also continue fixing bugs.

However, I cannot maintain the arch package itself because I do not use this distribution. Please make this clear when submitting the package to the repository.

Regards,
Stephan

**Comment by ShapeShifter499** [comment]
Hi Stephan,

I have created and uploaded the package to the AUR, you may find it at https://aur.archlinux.org/packages/splitviewfuse-git/  and  https://aur.archlinux.org/packages/splitviewfuse/        The -git appended version is a package most people using the AUR know will always pull in the latest code from git, so the actual AUR package will not get updated unless the script that builds your package is broken by a change. Any package without a -git, -svn, or other append usually known to be the latest release by a dev.   Can you also take a look at issue #5 again, I pointed out some unfixed issues.

Regards,
Lance

**Comment by ShapeShifter499** [comment]
I've updated the AUR packages so they will properly fetch the latest version. Feel free to save these links anywhere or add them to the readme.

**Comment by ShapeShifter499** [comment]
Since the packages download and install just fine from your git repository I'll close this.
